---
- name: provisioning AWS instances
  hosts: localhost

  vars:
    aws_region: us-east-2
    aws_key_name: my-key
    aws_security_group: launch-wizard-1
#    aws_key_file: /root/.ssh/my-key.pem
    aws_image: ami-0dd9f0e7df0f0a138

  tasks:
    - name: create key pair
      ec2_key:
        name: "{{ aws_key_name }}"
        region: "{{ aws_region }}"
      register: ec2_key_result

 #   - name: Save private key
 #     copy: content="{{ ec2_key_result.key.private_key }}" dest="./aws_key.pem" mode=0600

    - name: create 2 AWS ec2 instance
      ec2:
        key_name: "{{ aws_key_name }}"
#        security_group: "{{ aws_security_group }}"
        group_id: "sg-0cbcf09c7da4ea5f3"
        instance_type: "t2.micro"
        ec2_region: "{{ aws_region }}"
        image: "{{ aws_image }}"
        wait: yes
        count: 2
        vpc_subnet_id: subnet-19f3e463
        assign_public_ip: yes
      register: myvpc

    - name: Add new instance to host group build
      add_host:
        hostname: "{{ myvpc.instances[0].public_ip }}"
        groupname: build

    - name: Add new instance to host group web
      add_host:
        hostname: "{{ myvpc.instances[1].public_ip}}"
        groupname: web

    - name: Adding delay for system to come up
      wait_for:
        timeout: 30
      delegate_to: localhost

- name: build war
  hosts: build
  become: yes
  connection: ssh
  remote_user: ubuntu
  vars:
    ansible_ssh_private_key_file: ./aws_key.pem
  tasks:

    - name: enshure all packages are installed
      apt: pkg={{ item }} state=latest update_cache=yes
      with_items:
        - default-jdk
        - maven
        - git
        - python3-pip

    - name: Install boto3 python package
      pip:
        name: boto3

    - name: enshure repo cloned
      git: repo=https://github.com/boxfuse/boxfuse-sample-java-war-hello.git dest=/home/boxfuse-sample-java-war-hello
      tags: deploy

    - name: enshure package was built
      command: mvn package -f /home/boxfuse-sample-java-war-hello
    
    - name: Set AWS KEY ID
      set_fact: aws_key_id="{{ lookup('env','AWS_ACCESS_KEY_ID') }}"
      delegate_to: localhost
    - name: Set AWS SECRET
      set_fact: aws_secret_key="{{ lookup('env','AWS_SECRET_ACCESS_KEY') }}"
      delegate_to: localhost
    - name: Get AWS KEY ID
      set_fact: aws_key_id={{hostvars[inventory_hostname]['aws_key_id']}}
    - name: Get AWS SECRET KEY
      set_fact: aws_secret_key={{hostvars[inventory_hostname]['aws_secret_key']}}

    - name: put war to S3
      amazon.aws.aws_s3:
        aws_access_key: {{aws_key_id}}
        aws_secret_key: {{aws_secret_key}}
        bucket: testbucket.test5.com
        object: /my/hello-1.0.war
        src: /home/boxfuse-sample-java-war-hello/target/hello-1.0.war
        mode: put


- name: deploy to web instance
  hosts: web
  become: yes
  connection: ssh
  remote_user: ubuntu
  vars:
    ansible_ssh_private_key_file: ./aws_key.pem

  tasks:
    - name: ensure all packages is present
      #apt: pkg=tomcat9 state=present update_cache=yes
      apt: pkg={{ item }} state=present update_cache=yes
      with_items:
        - tomcat9
        - python3-pip

    - name: Install boto3 python package
      pip:
        name: boto3

    - name: Set AWS KEY ID
      set_fact: aws_key_id="{{ lookup('env','AWS_ACCESS_KEY_ID') }}"
      delegate_to: localhost
    - name: Set AWS SECRET
      set_fact: aws_secret_key="{{ lookup('env','AWS_SECRET_ACCESS_KEY') }}"
      delegate_to: localhost
    - name: Get AWS KEY ID
      set_fact: aws_key_id={{hostvars[inventory_hostname]['aws_key_id']}}
    - name: Get AWS SECRET KEY
      set_fact: aws_secret_key={{hostvars[inventory_hostname]['aws_secret_key']}}

    - name: Get an object.
      amazon.aws.aws_s3:
        aws_access_key: {{aws_key_id}}
        aws_secret_key: {{aws_secret_key}}
        bucket: testbucket.test5.com
        object: /my/hello-1.0.war
        dest: /var/lib/tomcat8/webapps/hello-1.0.war
        mode: get
